apiVersion: keda.sh/v1alpha1
kind: ScaledJob
metadata:
  name: c-code-execution-job
spec:
  jobTargetRef:
    template:
      spec:
        containers:
          - name: c-executor
            image: moitreyo/worker-container # This should be the image built from the Dockerfile
            env:
              - name: BROKER_URL
                value: amqp://guest:guest@rabbitmq-service.default.svc.cluster.local:5672
        restartPolicy: Never
  pollingInterval: 5
  successfulJobsHistoryLimit: 2
  failedJobsHistoryLimit: 5
  maxReplicaCount: 10
  triggers:
    - type: rabbitmq
      metadata:
        protocol: amqp
        queueName: c-code-queue
        mode: QueueLength
        value: "1"
        host: amqp://guest:guest@rabbitmq-service.default.svc.cluster.local:5672
